#!/bin/sh

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# SSH Agent
eval "$(ssh-agent -s)" > /dev/null 2>&1

# For GPG key signing
export GPG_TTY=$(tty)

# Clean-up Files in Home Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export NPM_CONFIG_PREFIX="$XDG_DATA_HOME/npm"
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"

export FREE_CAD_USER_HOME="$XDG_DATA_HOME/FreeCAD"

#Shell Cleanup
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/history"

#Programming Languages Cleanup:
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"


#ASDF
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"

export EDITOR="nvim"
export TERMINAL="wezterm"
export BROWSER="firefox"

# Start sway
if [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec sway
fi

